[project]
name = "quantum"
version = "0.4.0"
description = "A set of tools for quantum calculations."
readme = "README.md"
authors = [{ name = "kebasyaty", email = "kebasyaty@gmail.com" }]
requires-python = ">=3.12,<4.0"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"

[tool.uv]
package = true
compile-bytecode = true

[tool.uv.build-backend]
module-root = "src"
