# https://squidfunk.github.io/mkdocs-material/setup/
site_name: XLOFT Docs
repo_url: https://github.com/kebasyaty/xloft
repo_name: kebasyaty/xloft

theme:
  name: material
  font:
    text: Roboto
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - search.suggest
    - search.highlight
    - search.share
    # Minimum:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    # Extra:
    #- navigation.instant
    #- navigation.instant.progress
    #- navigation.tabs
    #- navigation.tabs.sticky
  palette:
    scheme: slate
    primary: indigo

extra_css:
  - github_style/css/extra.css

plugins:
  - search
  - git-authors
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  - tags:
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google

markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kebasyaty
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com

copyright: Copyright &copy; 2025 kebasyaty

nav:
  - XLOFT: index.md
  - Installation: installation.md
  - NamedTuple: namedtuple.md
  - Errors: errors.md
