# https://squidfunk.github.io/mkdocs-material/setup/
site_name: XLOFT Docs
site_description: "(XLOFT) X-Library of tools."
site_url: https://kebasyaty.github.io/xloft/
site_author: Gennady Kostyunin
copyright: Copyright &copy; 2025 Maintained by <a href="https://github.com/kebasyaty">Gennady Kostyunin</a>
repo_name: kebasyaty/xloft
repo_url: https://github.com/kebasyaty/xloft

theme:
  name: material
  font:
    text: Roboto
  icon:
    # https://pictogrammers.com/library/mdi/
    # logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  language: en
  features:
    - search.suggest
    - search.highlight
    - search.share
    # Minimum:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    # Extra:
    #- navigation.instant
    #- navigation.instant.progress
    #- navigation.tabs
    #- navigation.tabs.sticky
  palette:
    scheme: slate
    # github_black: indigo | github_blue: blue
    primary: blue

extra_css:
  # - custom_style/github_black.css
  - custom_style/github_blue.css

plugins:
  - search
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  - tags:
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google

markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kebasyaty
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com

nav:
  - XLOFT: index.md
  - Installation: md_pages/installation.md
  - NamedTuple: md_pages/namedtuple.md
  - Errors: md_pages/errors.md
