[project]
name = "humanism"
version = "0.1.0"
description = "A collection of instruments for converting data to format is convenient for humans."
readme = "README.md"
authors = [{ name = "kebasyaty", email = "kebasyaty@gmail.com" }]
requires-python = ">=3.12,<4.0"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
